version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "githubUsername=$GITHUB_USERNAME">~/.gradle/gradle.properties
      - echo "githubToken=$GITHUB_TOKEN">>~/.gradle/gradle.properties
  build:
    commands:
      - ./gradlew clean publish